name: cypress test

on:
  push:
    branches: [ "main", "dev" ]
jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          build: yarn build
          start: yarn start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120 # Sekunden warten, bis App gestartet ist
