name: CI Pipeline

on:
  push:
    branches: [ "main", "dev" ]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World"
              
      - name: executingremote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 2222
          script: echo "Hello World"
